config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    authenticated :user do
      root :to => 'topics#index'
    end

    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :topics do
    resources :questions do
      get 'statistics'
      get 'data'
      resources :answers
    end
  end

  get 'questions/:question_id/data' => 'answers#data'
  post 'question/:question_id/create' => 'answers#create'

end

app/models/question.rb
class Question < ActiveRecord::Base
  is_impressionable :through => :answers  #:unique => :request_hash to store unique sessions
  before_create :set_uuid
  self.primary_key = :uuid

  belongs_to :topic
  belongs_to :user
  has_many :choices, :dependent => :destroy
  has_many :answers, :dependent => :destroy

  accepts_nested_attributes_for :choices, reject_if: proc { |attributes| attributes['title'].blank?}, allow_destroy: true

  # VALIDATIONS
  validates :title,
    presence: true,
    length: {minimum: 6},
    uniqueness: {scope: :topic, case_sensitive: false , message: "Only once per topic"}

  private
    def set_uuid
      self.uuid = generate_uuid
    end

    def generate_uuid
      SecureRandom.uuid.gsub(/\-/,'')
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_topic
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_question_type, only: [:new, :create, :edit, :update]
  before_action :authenticate_user!, except: [ :index ]
  respond_to :html, :js

  def index
    @questions = @topic.questions.all
  end

  def show
    @answers = @question.answers.all
    @domain = request.base_url
    @tinyURL = TinyurlShortener.shorten(@domain + topic_question_answers_path(@topic, @question, @answer))
    @visits = @question.impressionist_count
  end

  def statistics
    @question = Question.find(params[:question_id])
    @answers = @question.answers
    @visits = @question.impressionist_count #:filter=>:session_hash
    calculate_engagement_rate(@question,@answers,@visits)
    @question.save!
  end

  def data
      questionsHash = @topic.questions.all
      @questionsArray = []
      @chartArray = []
      @answersObject = {name: "answers"}
      @visitsObject = {name: "visits"}
      @rateObject = {name: "engagement rate"}
      answers = []
      visits = []
      rates = []

      questionsHash.each do |q|
          answers.push([q['title'], q.answers.count])
          visits.push([q['title'], q.impressionist_count]) #:filter=>:session_hash
          rates.push([q['title'], q['engagement_rate']])
      end

      @answersObject[:data] = answers
      @visitsObject[:data] = visits
      @rateObject[:data] = rates
      @chartArray.push(@answersObject, @visitsObject, @rateObject)

    render :json => @chartArray
  end

  def new
    @question = @topic.questions.build
    @question.choices.build
  end

  def edit
  end

  def create
    @question = @topic.questions.build(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_to @topic, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @topic, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to @topic, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def set_question_type
      @question_types = [
        [ "Open Question", "Open Question"],
        [ "Multiple-choice", "Multiple-choice"],
        [ "True/False", "True/False"]
      ]
    end

    def set_topic
      @topic = Topic.friendly.find(params[:topic_id])
    end

    # CALCULATE ENGAGEMENT RATE
    def calculate_engagement_rate(question,answers,visits)
      if answers.count != 0
        question.engagement_rate = (answers.count*100)/(visits.nonzero? || 1)
          if question.engagement_rate.between? 0, 25
            @rate = 'POOR'
          elsif question.engagement_rate.between? 25, 50
            @rate = 'AVERAGE'
          elsif question.engagement_rate.between? 50, 75
            @rate = 'GOOD'
          elsif question.engagement_rate > 100
            question.engagement_rate = 100
          else
            @rate = 'EXCELLENT'
          end
      end
    end

    def question_params
      params.require(:question).permit(:title, :kind, :topic_id, :question_id, { choices_attributes: [:title, :question_id, :_destroy] })
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answerBox.html.erb
<div class="row">
  <% if @answers.any? %>
    <div id="lect-answers">
      <% @answers.each do |answer| %>
        <div class="col-sm-3">
          <div class="card">
            <div class="content">
              <h3><%= answer.value %></h3>
              <div class="footer">
                <hr>
                <div class="stats"><%= time_ago_in_words(answer.created_at) %></div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="col-sm-12">
      <h3 class="text-center">Your audience hasn't voted yet.</h3>
      <p class="category text-center">Please share the URL to your students </p>
    </div>
  <% end %>
</div>

app/views/questions/_choice_fields.html.erb
<div class="form-inline nested-fields">
  <%= f.text_field :title, placeholder: "Enter an answer choice", class: 'option', label_class: 'hidden' %>
  <%= link_to_remove_association 'Remove', f, class:"btn btn-danger btn-xs"%>
</div>

app/views/questions/_form.html.erb
<%= bootstrap_form_for [@topic,@question] do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :title, placeholder: 'Your Question' %>
  <%= f.select :kind, @question_types, { label: "Question Type" }, { class: "selectpicker" } %>
  <div id="custom_fields" style="display: none;">
    <%= f.fields_for :choices do |choice| %>
        <%= render 'choice_fields', :f => choice %>
        <div class="links"><br>
          <%= link_to_add_association 'add choice', f, :choices, class: 'btn btn-primary btn-xs' %>
        </div>
    <% end %>
  </div>
  <hr>
  <%= f.submit 'Create Question', class: 'btn btn-primary' %>
<% end %>

app/views/questions/edit.html.erb
<div class="page-header">
  <h1>Editing Question</h1>
</div>

<%= render 'form' %>
<hr>
<%= link_to 'Back', @topic, class: 'btn btn-default btn-xs' %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.kind %></td>
        <td><%= question.topic.title %></td>
        <td><%= link_to 'Show', [@topic, question] %></td>
        <td><%= link_to 'Edit', edit_topic_question_path(@topic, question) %></td>
        <td><%= link_to 'Destroy', [@topic, question], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/questions/new.html.erb
<div class="page-header">
  <h1>New Question</h1>
</div>

<%= render 'form' %>
<hr>
<%= link_to 'Back', @topic, class: 'btn btn-default btn-xs' %>

app/views/questions/show.html.erb
<script>
  var question_id = "<%= j @question.id.to_s %>";
</script>

<div class="screen">
  <div class="row">
    <div class="col-md-12">
      <%= render 'questions/partials/sections' %>
    </div>
  </div>

</div><!-- end screen -->

app/views/questions/statistics.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="card">
      <div class="header">
        <h2 class="title"><%= @question.title %></h2>
        <p class="category">A list of all the answers received for this question</p>
      </div>
      <div class="content">
        <div class="table-full-width">
          <table class="table">
            <tbody>
              <% @answers.each do |answer| %>
                <tr>
                  <!-- <td><label><%= display_username %></label></td> -->
                  <td><h4>"<%= answer.value %>"</h4><small><%= time_ago_in_words(answer.created_at) %> ago</small></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="footer">
          <hr>
          <div class="stats">
            <i class="glyphicon glyphicon-time"></i>
            Updated <%= time_ago_in_words(Time.now) %> ago
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="card">
      <div class="header">
        <h2 class="title">Student Engagement</h2>
        <p class="category">A comparisson between the number of visits and the number of answers</p>
      </div>
      <div class="content">
        <%= pie_chart answers: @answers.count,visits: @visits %>
        <div class="footer">
          <div class="category">
            Your Student Engagement Rate is <%= @question.engagement_rate %> %
          </div>
          <hr>
          <div class="stats">
            <i class="glyphicon glyphicon-time"></i>
            Updated <%= time_ago_in_words(Time.now) %> ago
          </div>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="header">
        <h2 class="title">Number of answers per minute</h2>
        <p class="category">See which part of the lecture is more likely to receive answers from students</p>
      </div>
      <div class="content">
        <%= line_chart @answers.group_by_minute %>
        <div class="footer">
          <div class="category">
          </div>
          <hr>
          <div class="stats">
            <i class="glyphicon glyphicon-time"></i>
            Updated <%= time_ago_in_words(Time.now) %> ago
          </div>
        </div>
      </div>
    </div>
    <div class="card">
      <div class="header">
        <h2 class="title">Most visited questions</h2>
        <p class="category">Compare question statistics</p>
      </div>
      <div class="content">
        <%= column_chart topic_question_data_path %>
        <div class="footer">
          <div class="category">
          </div>
          <hr>
          <div class="stats">
            <i class="glyphicon glyphicon-time"></i>
            Updated <%= time_ago_in_words(Time.now) %> ago
          </div>
        </div>
      </div>
    </div>
  </div>
</div>