config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    authenticated :user do
      root :to => 'topics#index'
    end

    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :topics do
    resources :questions do
      get 'statistics'
      get 'data'
      resources :answers
    end
  end

  get 'questions/:question_id/data' => 'answers#data'
  post 'question/:question_id/create' => 'answers#create'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  has_many :questions, :dependent => :destroy
  validates :title, presence: true, length: {minimum: 4}, uniqueness: {scope: :user}
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :index ]
  respond_to :html, :js

  def index
    @topics = current_user.topics.order('created_at desc')
    @topics_count = current_user.topics.count
  end

  def show
  end

  # GET /topics/new
  def new
    @topic = current_user.topics.build
  end

  def edit
  end

  def create
    @topic = current_user.topics.build(topic_params)
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_topic
      @topic = Topic.friendly.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:title)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/partials/_classroom.html.erb
<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.title %></td>
    <td class="td-actions text-right">
      <%= link_to 'Show', topic, class: 'btn btn-info btn-simple btn-sm' %>
      <%= link_to 'Edit', edit_topic_path(topic), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#classroom-modal', :class => 'btn btn-warning btn-simple btn-sm' } %>
      <%= link_to 'Destroy', topic, class: 'btn btn-danger btn-simple btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>

app/views/topics/partials/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h4>Create new classroom</h4>
    </div>
      <div class="modal-body">
        <%= bootstrap_form_for(@topic) do |f| %>
          <% if @topic.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

              <ul>
              <% @topic.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <%= f.text_field :title, placeholder: 'Insert classroom name' %>

          <div class="modal-footer">
            <%= f.submit 'Create Topic', class: 'btn btn-primary' %>
            <%= link_to "Cancel", "#", class: 'btn', data: {dismiss: 'modal'} %>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/topics/partials/_question.html.erb
<% @topic.questions.each do |q| %>
  <tr>
    <td><%= q.title %></td>
    <td><%= q.kind %></td>
    <td><%= q.created_at.strftime("%d %b. %Y") %></td>
    <td class="text-center"><%= q.engagement_rate %></td>
    <td class="td-actions text-right">
      <% if q.answers.any? %>
        <%= link_to topic_question_statistics_path(@topic, q), class: 'btn btn-simple', data: { toggle: 'tooltip'}, title: 'Statistics' do %>
          <i class="glyphicon glyphicon-stats text-info"></i>
        <% end %>
      <% end %>
      <%= link_to [@topic, q], class: 'btn btn-simple', data: { toggle: 'tooltip'}, title: 'See answers' do %>
          <i class="glyphicon glyphicon-comment text-primary"></i>
      <% end %>
      <%= link_to edit_topic_question_path(@topic, q), class: 'btn btn-simple', data: { toggle: 'tooltip'}, title: 'Edit' do %>
          <i class="glyphicon glyphicon-edit text-warning"></i>
      <% end %>
      <%= link_to [@topic, q], class: 'btn btn-danger btn-simple', method: :delete, data: { confirm: 'Are you sure?', toggle: 'tooltip' }, title: 'Delete' do %>
          <i class="glyphicon glyphicon-trash"></i>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/topics/partials/_questions_table.html.erb
<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Question</th>
      <th>Kind</th>
      <th>Date</th>
      <th class="text-center">Engagement Rate (%)</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render 'topics/partials/question' %>
  </tbody>
</table>

app/views/topics/partials/_table.html.erb
<table class="table table-hover table-striped">
  <tbody class="classroom-list">
    <%= render 'topics/partials/classroom' %>
  </tbody>
</table>