config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_scope :user do
    authenticated :user do
      root :to => 'topics#index'
    end

    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :topics do
    resources :questions do
      get 'statistics'
      get 'data'
      resources :answers
    end
  end

  get 'questions/:question_id/data' => 'answers#data'
  post 'question/:question_id/create' => 'answers#create'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  has_many :questions, :dependent => :destroy
  validates :title, presence: true, length: {minimum: 4}, uniqueness: {scope: :user}
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [ :index ]
  respond_to :html, :js

  def index
    @topics = current_user.topics.order('created_at desc')
    @topics_count = current_user.topics.count
  end

  def show
  end

  # GET /topics/new
  def new
    @topic = current_user.topics.build
  end

  def edit
  end

  def create
    @topic = current_user.topics.build(topic_params)
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_topic
      @topic = Topic.friendly.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:title)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<div class="page-header">
  <h1>Editing Topic</h1>
</div>

<%= render 'topics/partials/form' %>
<hr>
<%= link_to 'Show', @topic, class: 'btn btn-success btn-xs' %>
<%= link_to 'Back', topics_path, class: 'btn btn-default btn-xs' %>

app/views/topics/edit.js.erb
$('#classroom-modal').html("<%= j (render 'topics/partials/form')%>");

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="header">
        <h4 class="title">Classrooms <span class="badge"><%= @topics_count %></span></h4><br>
        <p class="category">
          <%= link_to "New Classroom", new_topic_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#classroom-modal', :class => 'btn btn-xs btn-simple btn-primary'}%>
        </p>
        <!-- <%= link_to "New Classroom", new_topic_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#classroom-modal', :class => 'btn btn-xs btn-primary'}%> -->
        <!--<%= link_to 'New Classroom', new_topic_path, remote: true, class: 'btn btn-xs btn-primary' %>-->
      </div>

        <% if @topics.any? %>
          <div class="content table-responsive table-full-width">
            <%= render 'topics/partials/table' %>
          </div>
        <% else %>
          <div class="content">
            <h4>Why don't you add a new topic?</h4>
          </div>
        <% end %>
    </div><!-- end card -->
  </div><!-- end col-md-12 -->
</div><!-- end row -->

<!-- Modal box is on the application.html.erb layout -->

app/views/topics/new.html.erb
<div class="page-header">
  <h1>New Topic</h1>
</div>

<%= render 'topics/partials/form' %>

<hr>
<%= link_to 'Back', topics_path, class: 'btn btn-default' %>

app/views/topics/new.js.erb
$('#classroom-modal').html("<%= j (render 'topics/partials/form')%>");

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="header">
        <h4 class="title"><%= @topic.title %>
          <%= link_to  new_topic_question_path(@topic), class: 'btn', data: { toggle: 'tooltip'}, title: 'Ask Question' do %>
              <i class="glyphicon glyphicon-plus text-primary"></i>
          <% end %>
        </h4>
          <p class="category">
            <!-- <%= link_to 'Add Question', new_topic_question_path(@topic), class: 'btn btn-sm btn-primary' %> -->
            <!-- <%= link_to 'Back', topics_path, class: 'btn btn-default btn-sm' %> -->
            A list of questions you've asked during the <span class="text-info"><%= @topic.title %></span> classroom
          </p>
      </div>

      <% if @topic.questions.any? %>
        <div class="content">
          <%= render 'topics/partials/questions_table' %>
        </div>
      <% else %>
        <div class="content">
          <h4>No Questions. Please add a new question!</h4>
        </div>
      <% end %>

    </div><!-- end card -->
  </div><!-- end col-md-12 -->
</div><!-- end row -->